# Generated by Django 6.0.1 on 2026-01-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('staff', 'Staff')], max_length=100),
        ),
    ]
